baseurl: https://johnmullane.eu/
canonifyURLs: true
disableFastRender: true
languageCode: en-IE
title: John Mullane
theme: hugo-lithium
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/JohnMullane-git
params:
  mainSections:
    - post
  highlightjs: false
  description: John Mullane website.
  logo:
    url: "jm_logo.jpg"
    width: 60
    height: 60
    alt: "John Mullane"

